### ISSUE TITLE
Filament usage empty

### ISSUE THREAD

**Issue by bastard** [imrahil/OctoPrint-PrintHistory#18]
Most of my prints do not have a value at filament usage. Yesterday I printed the same .gcode twice. Only one of them got a value in filament usage.

I would like to add the missing values by editing the file - would you please provide me the file format and a description of the fields.

**Comment by imrahil** [comment]
Hi,
sometimes there is no information about filament usage provided by Octoprint's core... 
if you want add it by yourself you have to edit history.yaml file in .octoprint/data/printhistory
filament usage is described by two fields:
```
filamentLength: 3794.7619700000037
filamentVolume: 9.127472187915986
```

**Comment by tedder** [comment]
@imrahil, discussing on an ancient ticket rather than opening the same issue. [the octoprint API has the estimated and 'consumed' filament info in the file interface](https://github.com/foosel/OctoPrint/blob/777c02135eeb256437081dfd81d1e0596b45ff4f/docs/api/datamodel.rst#gcode-analysis-information).
